texto = str(input("digite seu nome:"))
maiuscula = texto.upper()
print("o nome em letras maiusculas:")
print(maiuscula)
minuscula = texto.lower()
print("o nome em letras minusculas:")
print(minuscula)
numero = texto.strip()
print("o seu nome tem um total de {} letras".format(len(texto)-texto.count(" ")))
prnome = texto.split()
print("o seu primeiro nome é {} e tem {} letras".format(prnome[0],len(prnome[0])))
